Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -34,28 +34,50 @@ steps:
   persistCredentials: true
 
 - script: |
+    versionNumber="$(git show -s --format=%s)"
+
     echo "##[section]Setting Git username and email for pipeline"
     echo "Prior User Name: $(git config --get user.name)"
     echo "Prior Email: $(git config --get user.email)"
     git config user.email pipeline@pipeline.com & git config user.name "Pipeline"
-    versionNumber="$(git show -s --format=%s)"
+
     echo "##[section]Updating production branch"
     git checkout production
     git merge --squash "origin/$BRANCHNAME"
+
+    CONFLICTS=$(git ls-files -u | wc -l)
+    if [ "$CONFLICTS" -gt 0 ] ; then
+    echo "There is a merge conflict. Aborting"
+    git merge --abort
+    exit 1
+    fi
+
     echo "##[section]Committing changes"
     git commit -m "v$versionNumber"
+
     echo "##[section]Tagging commit"
     git tag "v$versionNumber"
-    echo "##[section]Pushing changes to origin/production"
-    git push --set-upstream origin production --tags
-    git push origin --tags
+
     echo "##[section]Updating development branch"
     git checkout development
     git merge --squash "origin/$BRANCHNAME"
+
+    CONFLICTS=$(git ls-files -u | wc -l)
+    if [ "$CONFLICTS" -gt 0 ] ; then
+    echo "There is a merge conflict. Aborting"
+    git merge --abort
+    exit 1
+    fi
+
     echo "##[section]Committing changes"
     git commit -m "v$versionNumber"
-    echo "##[section]Pushing changes to origin/development"
+
+    echo "##[section]Pushing changes to origin"
     git push --set-upstream  origin development
+    gi checkout production
+    git push --set-upstream origin production --tags
+    git push origin --tags
+
     echo "##[section]Deleting branch $BRANCHNAME"
     git push -d origin "$BRANCHNAME"
   displayName: Bump version
